[[redirects]]
  from = "https://gateway.ipfs.io/"
  to = "https://bezata.netlify.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"